### ISSUE TITLE
not be able to install the package 

### ISSUE THREAD

**Issue by jqian2015** [NormanLabUCD/PONG#1]
I tried to download or install your package as you mentioned in 'Pong User Pipeline and Tutorial’ but had some errors. Also tried install_github("NormanLabUCD/PONG”) but did not work. Would you please tell me how exactly I can install your package?

Btw, by git clone or download code from GitHub, it seemed that all I got were wrong/empty  files without any contents. Not sure why though.  

Thanks a lot for your time and help.

Jun

**Comment by laleaton** [comment]
Hi Jun,
Thank you for your message and we apologize for the inconvenience. To install PONG, try downloading the zipped file to your computer, then running the following in the terminal:
```
unzip KIRpong-master.zip
R CMD build KIRpong-master/
gunzip KIRpong.1.0.0.tar.gz
R CMD INSTALL KIRpong/
```
Feel free to email me directly if you run into further issues.
Laura Ann
laura.leaton@cuanschutz.edu

**Comment by jqian2015** [comment]
hi Lauran, thanks for the tips. Finally I made the package work and some errors are listed below in case someone else might be interested and has same questions. 

1. since git-lfs has to be installed before using git clone, it would be very helpful if this tip can be written in readme.
2.  in the Pong User Pipeline and Tutorial.pdf, last line needs to be corrected into:

write.table(pred.guess_value, paste0(path_inputs, "/inst/extdata/Results/Chr19.hg38_TGP_EUR_Populations_Results_Prediction_Alleles_v31txt"),quote=F,sep="\t",row.names=F,col.names=T)

otherwise, the original code will lead to a wrong file name which is the main cause we will have error when using 'git clone’ on windows or when trying to build/install on Mac.

3. the description and namesapce files need to be cleaned up by removing head/tail 

once these three bugs be fixed, the source files should be fine with building and ready for the installation. 

4. again, in the Pong User Pipeline and Tutorial.pdf, predic() might need to be replaced with predict.hlaAttrBagClass().

other than the bugs mentioned above, the tool runs well. Thanks again for the help and it is a great tool.

**Comment by laleaton** [comment]
thanks for your helpful comments!
