### ISSUE TITLE
trouble installing the package

### ISSUE THREAD

**Issue by jqian2015** [NormanLabUCD/PONG#2]
first of all, i downloaded PONG-master.zip, which is not KIRpong-master.zip.

and followed your instructions but still had errors like this: 

C:\Users\Jack\Downloads>R CMD build KIRpong-master/
 ERROR
cannot change to directory 'KIRpong-master'

C:\Users\Jack\Downloads>R CMD build PONG-master/
* checking for file 'PONG-master/DESCRIPTION' ... NO

as i mentioned earlier, the files in the downloaded zip files are empty. 

would be greatly appreciated if more specific instructions can be given. thanks.

**Comment by jqian2015** [comment]
Is that ok if you can just send me the raw KIRpong-master.zip file directly? Thanks.

**Comment by laleaton** [comment]
Please refer to updated install instructions in the user manual at https://github.com/NormanLabUCD/PONG/tree/master/inst/doc
